{
 "title": "HelpDesk Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(django_http_requests_total_by_method_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Views rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_view_method_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Load on Instance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\t100 - (avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}