global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'helpdesk-backend'
    metrics_path: /metrics/
    scheme: http
    static_configs:
      - targets: ['helpdesk-backend:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_token
        replacement: supersecret
