server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrapre_configs:
- job_name: django
  static_configs:
  - targets:
    - localhost
    labels:
      job: django_logs
      __path__: /var/log/django/*log