global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'helpdesk-backend'
    metrics_path: /metrics/
    scheme: http
    static_configs:
      - targets: ['helpdesk-backend:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_token
        replacement: supersecret

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
