# Generated by Django 5.2 on 2025-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image_after",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/after"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="image_before",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/before"),
        ),
    ]
