# Generated by Django 5.2 on 2025-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_image_after_ticket_image_before"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="image_after",
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comments/"),
        ),
    ]
